version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile-prod
    depends_on:
      - db
    command:
      [
        './wait-for-it.sh',
        'db:3306',
        '--',
        'bash',
        '-c',
        'cd server && npx sequelize-cli db:migrate && cd .. && node server/index.js',
      ]
    ports:
      - 80:80
    working_dir: '/usr/src/app'
    restart: always
    environment:
      - NODE_ENV=production
      - SERVER_PORT=80
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
  db:
    image: mysql:8
    expose:
      - '3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./db:/var/lib/mysql
